import Login from '@/components/Login/Login';
import styles from './page.module.scss';
import { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Grid Color',
  description: 'Generated by create next app',
};

export default function Home() {
  return (
    <main className={styles['container']}>
      <h1>Welcome to Grid color</h1>

      <Login />
    </main>
  );
}
