import styles from './page.module.scss';
import { Metadata } from 'next';
import Link from 'next/link';

export const metadata: Metadata = {
  title: 'Grid Color',
  description: 'Generated by create next app',
};

export default function Home() {
  return (
    <main className={styles['container']}>
      <Link href={'/grid'}>
        <h1>Go to the grid</h1>
      </Link>
    </main>
  );
}
