import styles from './page.module.scss';
import { Metadata } from 'next';
import HeaderGrid from '../components/Grid/HeaderGrid/HeaderGrid';
import GridColor from '../components/Grid/GridColor';
import Waiting from '../components/Waiting/Waiting';

export const metadata: Metadata = {
  title: 'Grid Color',
  description: 'Generated by create next app',
};

export default function Home() {
  return (
    <main className={styles['container']}>
      <HeaderGrid />
      <GridColor />
      <Waiting />
    </main>
  );
}
