import HeaderGrid from '@/components/Grid/HeaderGrid/HeaderGrid';
import { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Grid Color',
  description: 'Generated by create next app',
};

const Grid = () => {
  return (
    <div>
      <HeaderGrid />
    </div>
  );
};

export default Grid;
