import GridColor from '@/components/Grid/GridColor';
import HeaderGrid from '@/components/Grid/HeaderGrid/HeaderGrid';
import { Metadata } from 'next';
import styles from './page.module.scss';

export const metadata: Metadata = {
  title: 'Grid Color',
  description: 'Generated by create next app',
};

const Grid = () => {
  return (
    <div className={styles['container']}>
      <HeaderGrid />
      <GridColor />
    </div>
  );
};

export default Grid;
